#!/usr/bin/env python

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


import argparse
import multiprocessing

from middleman.api import app, configure_app


def develop(args):
   global app
   app = configure_app(app, args.configuration)
   app.run(host=args.address, port=args.port, debug=args.debug, use_reloader=args.reload)

def run(args):
   print "TODO Implement GUnicorn support"


if __name__ == "__main__":

   parser = argparse.ArgumentParser(prog="middleman-api")
   sub_parsers = parser.add_subparsers()

   develop_parser = sub_parsers.add_parser("develop")
   develop_parser.add_argument("-a", "--address", default="127.0.0.1")
   develop_parser.add_argument("-p", "--port", default=8080)
   develop_parser.add_argument("-c", "--configuration")
   develop_parser.add_argument("-d", "--debug", default=True)
   develop_parser.add_argument("-r", "--reload", default=True)
   develop_parser.set_defaults(func=develop)

   run_parser = sub_parsers.add_parser("run")
   run_parser.add_argument("-a", "--address", default="127.0.0.1")
   run_parser.add_argument("-p", "--port", default=8080)
   run_parser.add_argument("-c", "--configuration")
   run_parser.add_argument("-w", "--workers", default=multiprocessing.cpu_count() * 2 + 1)
   run_parser.set_defaults(func=run)

   args = parser.parse_args()
   args.func(args)
