#!/usr/bin/env python

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/

import sys
import rq

import selenium


with rq.Connection():
    qs = map(rq.Queue, sys.argv[1:]) or [rq.Queue()]
    w = rq.Worker(qs)
    w.work()
